version: 1.0.0

component:
  name: sentiment-analysis-api
  type: api
  runtime: python3.8
  
  env:
    - name: FLASK_ENV
      value: development

  resources:
    cpu: 500m
    memory: 512Mi

  ports:
    - protocol: HTTP
      port: 5000

entrypoint:
  command: python
  args: ["flask_app.py"]
